# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58477440e62c05ce953e361e8c4534773cd170139a0a707ad783cf1a1d9ee525b966420651fbe8f8f31dea64d7085b024c45f5208274f7db1c84d1fbad53b043

test:
  secret_key_base: 22fd4b4255705b03a5e19b5831e55d891717586968efa2f2680851efbd39fc00d246fb4eebccf0742191f6c19e52a0d12048b1d16ac9d218816f3fb365bccbcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
